version: '3.7'

services:
  app:
    build: app
    restart: always
    volumes:
      - ./app/src:/code
    depends_on:
      - redis
    ports:
      - "5000:5000"
  redis:
    image: redis
    ports:
      - "6379:6379"